name: Upload Source Maps to Sentry

on:
  push:
    branches:
      - main
      - development

env:
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  NEXT_PUBLIC_CHAIN_ID: uni-6
  NEXT_PUBLIC_CHAIN_NAME: NEXT_PUBLIC_CHAIN_NAME
  NEXT_PUBLIC_CHAIN_RPC_ENDPOINT: NEXT_PUBLIC_CHAIN_RPC_ENDPOINT
  NEXT_PUBLIC_CHAIN_REST_ENDPOINT: NEXT_PUBLIC_CHAIN_REST_ENDPOINT
  NEXT_PUBLIC_FEE_DENOM: NEXT_PUBLIC_FEE_DENOM
  NEXT_PUBLIC_STAKING_DENOM: NEXT_PUBLIC_STAKING_DENOM
  NEXT_PUBLIC_SITE_URL: NEXT_PUBLIC_SITE_URL
  NEXT_PUBLIC_SITE_IMAGE: NEXT_PUBLIC_SITE_IMAGE
  NEXT_PUBLIC_DAO_DAO_VERSION: NEXT_PUBLIC_DAO_DAO_VERSION
  NEXT_PUBLIC_CHAIN_TXN_URL_PREFIX: NEXT_PUBLIC_CHAIN_TXN_URL_PREFIX
  NEXT_PUBLIC_DAO_ADDRESS: NEXT_PUBLIC_DAO_ADDRESS
  NEXT_PUBLIC_VOTE_EXTERNAL_URL: NEXT_PUBLIC_VOTE_EXTERNAL_URL
  NEXT_PUBLIC_AIRDROP_URL: NEXT_PUBLIC_AIRDROP_URL
  NEXT_PUBLIC_SEARCH_URL: NEXT_PUBLIC_SEARCH_URL
  NEXT_PUBLIC_SEARCH_API_KEY: NEXT_PUBLIC_SEARCH_API_KEY
  NODE_OPTIONS: --max_old_space_size=4096
jobs:
  ci:
    name: Lint, Build, & Upload
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'yarn'
      - run: yarn install
      - run: yarn lint
      - run: yarn dapp build
      - run: yarn sda build
